### ISSUE TITLE
Doesn't play well with Dark Mode

### ISSUE THREAD

**Issue by balthisar** [DangerCove/DCOAboutWindow#10]
I'll take a look at it time permitting (a lot of other frameworks I use have a similar issue). Just logging it here.

Description: in Mojave, switching to dark mode does not update the window background.

**Comment by balthisar** [comment]
Added PR #11 to address this.

**Comment by boyvanamstel** [comment]
Your changes have been merged! Use the new delegate to preprocess the credits for Dark Mode. :)
